stages:
  data_ingestion:
    cmd: python src/covid_classifier/pipeline/stage_01_data_ingestion.py
    deps:
    - src/covid_classifier/pipeline/stage_01_data_ingestion.py
    - configs/config.yaml
    outs:
    - artifacts/data_ingestion/covid19-image-dataset/Covid19-dataset

  data_validation:
    cmd: python src/covid_classifier/pipeline/stage_02_data_validation.py
    deps:
    - src/covid_classifier/pipeline/stage_01_data_ingestion.py
    - src/covid_classifier/pipeline/stage_02_data_validation.py
    - configs/config.yaml
    outs:
    - artifacts/data_validation/Covid19-dataset

  prepare_base_model:
    cmd: python src/covid_classifier/pipeline/stage_03_prepare_base_model.py
    deps:
    - src/covid_classifier/pipeline/stage_03_prepare_base_model.py
    - configs/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
    - artifacts/prepare_base_model

  training:
      cmd: python src/covid_classifier/pipeline/stage_04_training.py
      deps:
      - src/covid_classifier/pipeline/stage_04_training.py
      # - src/covid_classifier/components/prepare_callback.py
      - configs/config.yaml
      - artifacts/data_ingestion/covid19-image-dataset/Covid19-dataset
      - artifacts/prepare_base_model
      params:
        - IMAGE_SIZE
        - INCLUDE_TOP
        - CLASSES
        - WEIGHTS
        - LEARNING_RATE
      outs:
        - artifacts/model_training/model.h5
        - artifacts/model_training/score.txt
