artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.kaggle.com/datasets/pranavraikokte/covid19-image-dataset
  local_data_file: artifacts/data_ingestion/Covid19-dataset
  local_data_file_train: artifacts/data_ingestion/Covid19-dataset/train
  local_data_file_test: artifacts/data_ingestion/Covid19-dataset/test
  
data_validation:
  root_dir: artifacts/data_validation
  validated_local_data_file: artifacts/data_validation/Covid19-dataset
  validated_local_data_file_train: artifacts/data_validation/Covid19-dataset/train
  validated_local_data_file_test: artifacts/data_validation/Covid19-dataset/test